/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co_templates;

import co_templates.controller.AttendanceController;
import co_templates.repository.AttendanceRepository;
import co_templates.service.EmpDailyRecordsService;
import co_templates.service.EmpQueryService;
import co_templates.view.HRView;

public class App {

    public static void main(String[] args) {
        AttendanceRepository attendanceRepository = new AttendanceRepository();
        EmpDailyRecordsService empDailyRecordsService = new EmpDailyRecordsService();
        EmpQueryService empQueryService = new EmpQueryService(attendanceRepository);
        HRView hrView = new HRView();

        AttendanceController attendanceController = new AttendanceController(
                attendanceRepository,
                empDailyRecordsService,
                empQueryService,
                hrView);

        attendanceController.run();


    }
}
