/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package co_templates;

import co_templates.controller.AttendanceController;
import co_templates.repository.AttendanceRepository;
import co_templates.view.HRView;

import java.sql.SQLException;

public class App {

    public static void main(String[] args) {
        AttendanceRepository attendanceRepository = new AttendanceRepository();
        HRView hrView = new HRView();


        AttendanceController attendanceController
                = new AttendanceController(attendanceRepository, hrView);

        attendanceController.run();
    }
}
